import { useEffect, useMemo, useState } from "react";
import { Check, Coins, Crown, Gem, LoaderCircle, Radio, Search, ShoppingBag, Sparkles, WandSparkles, X } from "lucide-react";
import { activeAccount, useLauncherStore } from "../store/launcherStore";
import { buyCosmetic, equipCosmetic, loadShop, unequipCosmetic, type ShopSnapshot } from "../lib/shop";
import type { Cosmetic } from "../types";
const LABELS: Record<string,string>={all:"Alle",cape:"Capes",wings:"Wings",hat:"Hüte",halo:"Halos",shoulder:"Buddies",bandana:"Bandanas",glint:"Glints",emote:"Emotes"};
function Icon({type}:{type:string}){if(type==="wings"||type==="cape")return <Sparkles/>;if(type==="glint"||type==="halo")return <Gem/>;if(type==="emote")return <WandSparkles/>;return <Crown/>}
export function ShopPage(){
 const {snapshot,setPage}=useLauncherStore(); const account=activeAccount(snapshot); const [shop,setShop]=useState<ShopSnapshot|null>(null); const [category,setCategory]=useState("all"); const [query,setQuery]=useState(""); const [loading,setLoading]=useState(true); const [syncing,setSyncing]=useState(false); const [actionId,setActionId]=useState<string|null>(null); const [error,setError]=useState<string|null>(null); const [notice,setNotice]=useState<string|null>(null);
 const reload=async(show=true)=>{if(!snapshot||!account)return;show?setLoading(true):setSyncing(true);try{setShop(await loadShop(account,snapshot.settings));setError(null)}catch(e){if(show)setError(e instanceof Error?e.message:String(e))}finally{show?setLoading(false):setSyncing(false)}};
 useEffect(()=>{void reload(true)},[account?.id]);
 useEffect(()=>{if(!account)return;const sync=()=>void reload(false);const timer=window.setInterval(sync,2500);window.addEventListener("focus",sync);document.addEventListener("visibilitychange",sync);return()=>{clearInterval(timer);window.removeEventListener("focus",sync);document.removeEventListener("visibilitychange",sync)}},[account?.id,snapshot?.settings.backend_url]);
 const cats=useMemo(()=>["all",...Array.from(new Set(shop?.catalog.map(i=>i.type.toLowerCase())??[]))],[shop?.catalog]); const filtered=useMemo(()=>{const t=query.trim().toLowerCase();return(shop?.catalog??[]).filter(i=>(category==="all"||i.type.toLowerCase()===category)&&(!t||`${i.name} ${i.description} ${i.type}`.toLowerCase().includes(t)))},[shop?.catalog,category,query]);
 if(!snapshot||!account)return <div className="page"><div className="empty-state"><ShoppingBag/><h2>Kein Account aktiv</h2><button className="button button--primary" onClick={()=>setPage("accounts")}>Account hinzufügen</button></div></div>;
 const run=async(item:Cosmetic,kind:"buy"|"equip"|"unequip")=>{if(!shop||actionId)return;setActionId(item.id);setError(null);try{const profile=kind==="buy"?await buyCosmetic(account,snapshot.settings,shop.token,item.id,item.type):kind==="equip"?await equipCosmetic(account,snapshot.settings,shop.token,item.id,item.type):await unequipCosmetic(account,snapshot.settings,shop.token,item.id,item.type);setShop({...shop,profile});setNotice(kind==="buy"?`${item.name} gekauft.`:kind==="equip"?`${item.name} dauerhaft ausgerüstet.`:`${item.name} abgelegt.`);await reload(false)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setActionId(null)}};
 return <div className="page shop-page"><header className="page-header shop-header"><div><span className="eyebrow">S9 STORE</span><h1>Cosmetics & Inventar</h1><p>Kaufen und dauerhaft mit deinem Minecraft-Profil synchronisieren.</p></div><div className="shop-status-row"><div className="live-sync"><Radio size={14}/><span>{syncing?"SYNC…":"SERVER-SYNC"}</span></div><div className="coin-wallet"><Coins/><div><span>COINS</span><strong>{shop?.profile.coins.toLocaleString("de-DE")??"—"}</strong></div></div></div></header>
 <div className="shop-toolbar panel"><div className="shop-categories">{cats.map(v=><button key={v} className={category===v?"shop-category shop-category--active":"shop-category"} onClick={()=>setCategory(v)}>{LABELS[v]??v}</button>)}</div><div className="shop-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cosmetics durchsuchen"/></div></div>
 {error&&<div className="friends-error">Shop: {error}</div>}{notice&&<div className="shop-notice"><Check size={15}/>{notice}</div>}
 {loading?<div className="friends-loading"><LoaderCircle className="spin"/> Shop wird geladen…</div>:<div className="shop-grid shop-grid--no-preview">{filtered.map(item=>{const owned=shop?.profile.ownedCosmetics.includes(item.id)??false;const equipped=shop?.profile.equippedCosmetics[item.type]===item.id;const affordable=(shop?.profile.coins??0)>=item.price;return <article className={`shop-card shop-card--simple ${equipped?"shop-card--equipped":""}`} key={item.id}><div className="shop-card__icon"><Icon type={item.type.toLowerCase()}/>{equipped&&<span>AUSGERÜSTET</span>}</div><div className="shop-card__body"><small>{LABELS[item.type.toLowerCase()]??item.type}</small><h2>{item.name}</h2><p>{item.description||"S9Lab Cosmetic"}</p><div className="shop-card__footer"><div className="shop-price"><Coins size={14}/><strong>{item.price.toLocaleString("de-DE")}</strong></div>{!owned?<button className="shop-buy" disabled={!affordable||actionId!==null} onClick={()=>void run(item,"buy")}>{actionId===item.id?<LoaderCircle className="spin"/>:affordable?"KAUFEN":"ZU WENIG COINS"}</button>:equipped?<button className="shop-buy shop-buy--unequip" onClick={()=>void run(item,"unequip")} disabled={actionId!==null}><X size={14}/>ABLEGEN</button>:<button className="shop-buy shop-buy--equip" onClick={()=>void run(item,"equip")} disabled={actionId!==null}><Check size={14}/>AUSRÜSTEN</button>}</div></div></article>})}</div>}
 </div>;
}
