import { useEffect, useMemo, useRef, useState } from "react";
import { Check, LoaderCircle, MessageCircle, Search, Send, Trash2, UserPlus, Users, X } from "lucide-react";
import { activeAccount, useLauncherStore } from "../store/launcherStore";
import { addFriend, createBackendSession, getFriendMessages, getFriends, removeFriend, respondFriend, sendFriendMessage, type Friend, type FriendMessage, type FriendsResponse } from "../lib/friends";

export function FriendsPage(){
 const {snapshot,setPage}=useLauncherStore(); const account=activeAccount(snapshot); const [data,setData]=useState<FriendsResponse|null>(null); const [token,setToken]=useState<string|null>(null); const [name,setName]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [selected,setSelected]=useState<Friend|null>(null); const [messages,setMessages]=useState<FriendMessage[]>([]); const [draft,setDraft]=useState(""); const [chatLoading,setChatLoading]=useState(false); const endRef=useRef<HTMLDivElement|null>(null);
 const load=async()=>{if(!snapshot||!account)return;setLoading(true);setError(null);try{const t=token??await createBackendSession(account,snapshot.settings);setToken(t);setData(await getFriends(snapshot.settings,t));}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setLoading(false);}};
 useEffect(()=>{setToken(null);setSelected(null);setMessages([]);void load();},[account?.id]);
 useEffect(()=>{if(!snapshot||!token||!selected)return;let stop=false;const refresh=async()=>{try{const r=await getFriendMessages(snapshot.settings,token,selected.uuid);if(!stop)setMessages(r.messages);}catch(e){if(!stop)setError(e instanceof Error?e.message:String(e));}finally{if(!stop)setChatLoading(false);}};setChatLoading(true);void refresh();const id=window.setInterval(()=>void refresh(),3500);return()=>{stop=true;window.clearInterval(id);};},[selected?.uuid,token]);
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"});},[messages.length]);
 const mutate=async(task:(t:string)=>Promise<FriendsResponse>)=>{if(!token)return;try{setError(null);setData(await task(token));}catch(e){setError(e instanceof Error?e.message:String(e));}};
 const send=async()=>{if(!snapshot||!token||!selected||!draft.trim())return;const text=draft.trim();setDraft("");try{const m=await sendFriendMessage(snapshot.settings,token,selected.uuid,text);setMessages(v=>[...v,m]);}catch(e){setDraft(text);setError(e instanceof Error?e.message:String(e));}};
 const selectedUuid=selected?.uuid;
 const currentFriend=useMemo(()=>data?.friends.find(f=>f.uuid===selectedUuid)??selected,[data?.friends,selectedUuid]);
 if(!snapshot||!account)return <div className="page friends-page"><div className="empty-state"><Users size={34}/><h2>Kein Account aktiv</h2><p>Melde dich an, um Freunde und Nachrichten zu sehen.</p><button className="button button--primary" onClick={()=>setPage("accounts")}>Account hinzufügen</button></div></div>;
 return <div className="page friends-page"><header className="page-header"><div><span className="eyebrow">S9 SOCIAL</span><h1>Freunde & Nachrichten</h1><p>Freunde verwalten und direkt mit ihnen schreiben.</p></div></header>
 <div className="friends-toolbar panel"><div className="friend-search"><Search size={16}/><input value={name} onChange={e=>setName(e.target.value)} placeholder="Spielername eingeben" onKeyDown={e=>{if(e.key==='Enter'&&name.trim())void mutate(t=>addFriend(snapshot.settings,t,name.trim())).then(()=>setName(''));}}/></div><button className="button button--primary" disabled={!name.trim()||!token} onClick={()=>void mutate(t=>addFriend(snapshot.settings,t,name.trim())).then(()=>setName(''))}><UserPlus size={16}/> Anfrage senden</button></div>
 {error&&<div className="friends-error">Backend: {error}</div>}
 {loading?<div className="friends-loading"><LoaderCircle className="spin"/> Freunde werden geladen…</div>:<div className="social-chat-layout">
  <aside className="panel social-roster"><header><h2>Freunde</h2><span>{data?.friends.length??0}</span></header><div className="social-roster__list">{data?.friends.map(friend=><button key={friend.uuid} className={selected?.uuid===friend.uuid?"friend-select friend-select--active":"friend-select"} onClick={()=>setSelected(friend)}><i className={friend.online?"friend-presence friend-presence--online":"friend-presence"}/><span><strong>{friend.name}</strong><small>{friend.online?friend.status:"Offline"}</small></span>{friend.unreadMessages>0&&<b>{friend.unreadMessages}</b>}<MessageCircle size={15}/></button>)}{!data?.friends.length&&<div className="friends-empty">Noch keine Freunde hinzugefügt.</div>}</div>
  <section className="requests-compact"><h3>Anfragen ({data?.incomingRequests.length??0})</h3>{data?.incomingRequests.map(req=><div className="request-compact" key={req.uuid}><span>{req.name}</span><button onClick={()=>void mutate(t=>respondFriend(snapshot.settings,t,req.uuid,true))}><Check size={14}/></button><button onClick={()=>void mutate(t=>respondFriend(snapshot.settings,t,req.uuid,false))}><X size={14}/></button></div>)}</section></aside>
  <section className="panel chat-panel">{currentFriend?<><header className="chat-header"><div><strong>{currentFriend.name}</strong><span>{currentFriend.online?currentFriend.status:"Offline"}</span></div><button className="icon-button danger" title="Freund entfernen" onClick={()=>void mutate(t=>removeFriend(snapshot.settings,t,currentFriend.uuid)).then(()=>setSelected(null))}><Trash2 size={15}/></button></header><div className="chat-messages">{chatLoading?<div className="friends-loading"><LoaderCircle className="spin"/> Verlauf wird geladen…</div>:messages.length?messages.map(m=>{const mine=m.senderUuid.replaceAll('-','')===account.id.replaceAll('-','');return <div key={m.messageId} className={mine?"chat-message chat-message--mine":"chat-message"}><span>{mine?"Du":m.senderName}</span><p>{m.message}</p><time>{new Date(m.sentAt*1000).toLocaleString("de-DE",{hour:"2-digit",minute:"2-digit",day:"2-digit",month:"2-digit"})}</time></div>}):<div className="chat-empty"><MessageCircle size={34}/><strong>Noch keine Nachrichten</strong><span>Starte die Unterhaltung.</span></div>}<div ref={endRef}/></div><div className="chat-composer"><textarea value={draft} onChange={e=>setDraft(e.target.value.slice(0,500))} placeholder={`Nachricht an ${currentFriend.name}`} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send();}}}/><button className="button button--primary" disabled={!draft.trim()} onClick={()=>void send()}><Send size={16}/></button></div></>:<div className="chat-empty"><Users size={38}/><strong>Wähle einen Freund</strong><span>Dann kannst du den Nachrichtenverlauf öffnen.</span></div>}</section>
 </div>}</div>;
}
